item {
	id: 1
	name: 'blackcherry'
}

item {
	id: 2
	name: 'lemon'
}

item {
	id: 3
	name: 'lemonade'
}

item {
	id: 4
	name: 'lime'
}

item {
	id: 5
	name: 'blood_orange'
}

item {
	id: 6
	name: 'pineapple'
}

item {
	id: 7
	name: 'competitor_01'
}

item {
	id: 8
	name: 'competitor_02'
}
